version: '2'

services:
  twittervotes:
    build: ./twittervotes
    env_file: ./twittervotes/.env
    depends_on:
      - db
      - nsqlookupd
      - nsqd
    networks:
      - local

  db:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - mongo-data:/data/db
    command: mongod --smallfiles
    ports:
      - "27017:27017"
    networks:
      - local

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "4160"
      - "4161"
    networks:
      - local
    
  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    ports:
      - "4150"
      - "4151"
    depends_on:
      - nsqlookupd
    networks:
      - local
    
  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "4171:4171"
    depends_on:
      - nsqd
    networks:
      - local

volumes:
  mongo-data:

networks:
  local:
